### PR TITLE
refactor: wrap column name string to column value class

### PR DESCRIPTION
**Pull request by hsgwa**
Signed-off-by: hsgwa <hasegawa.isp@gmail.com>

Currently, column management is complicated inside CARET_analyze implementations.
This PR wraps column names into classes.
I'll will continue refactoring by adding attributes(e.g. simtime / systemtime) to ColumnValue, etc.

NOTE: This PR is a partial backport of v0.4.

### CODE REVIEW

**Review by takam5f2 — DISMISSED** [review]
LGTM

**Comment by takam5f2** [comment]
@hsgwa  Could you resolve the conflict?

**Comment by hsgwa** [comment]
@takam5f2 
I fixed a merge conflict. Could you review this PR again?

**Review by takam5f2 — APPROVED** [review]
LGTM!

**Pull request merged**
