### PR TITLE
fix: error with empty records

### PR DESCRIPTION
**Pull request by rokamu623**
## Description
A problem with the histogram terminating in error when an empty Records is inputted has been resolved.
After the resolve, an empty histogram is displayed.

image

## Related links
Jira: https://tier4.atlassian.net/browse/RT2-1202

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR has been properly tested.
- [x] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Comment by rokamu623** [comment]
@taro-yu 
Please review.

**Comment by rokamu623** [comment]
@taro-yu or @emori-ctc 
Please review.

**Review by taro-yu — APPROVED** [review]
LGTM!

**Review by xygyo77 — APPROVED** [review]
image

LGTM

**Pull request merged**
