### PR TITLE
refactor(records): clean RecordFactory.create_instance

### PR DESCRIPTION
**Pull request by hsgwa**
Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>

This PR is a refactoring of RecordFactory.create_instance.

Before
```
 record = RecordFactory.create_instance({'column': 0})
```

After
```
 {'column': 0}
```

### CODE REVIEW

**Comment by hsgwa** [comment]
I'll close once because the following error occurs only within the github action.
This may change we move our testing environment to humble.
```
FAILED src/test/test_flake8.py::test_flake8 - AssertionError: Found 2 code style errors / warnings:
  ./src/caret_analyze/architecture/architecture.py:156:5: F811 redefinition of unused 'publishers' from line 146
  ./src/caret_analyze/architecture/architecture.py:161:5: F811 redefinition of unused 'subscriptions' from line 151
```

**Review by rokamu623 — CHANGES_REQUESTED** [review]
```
record = {
  ...
}
records.append(record)
```
and
```
records.append({
  ...
})
```
implementations are mixed.

If the above is acceptable, I will approve it.

**Comment by takam5f2** [comment]
@hsgwa  
I think that it is acceptable if you check the comment from @rokamu623.

**Review by rokamu623 — APPROVED** [review]
LGTM!

**Pull request merged**
