### PR TITLE
fix: public caret api annotations and some codes in application.py

### PR DESCRIPTION
**Pull request by taro-yu**
## Description

The purpose of this PR is to make corrections to the code resulting from the annotation modification. The separate PR(https://github.com/tier4/caret_analyze/pull/488) corrects the docs and annotations, but this PR corrects the processing code in addition to the docs and annotations.

## Related links

- https://tier4.atlassian.net/browse/RT2-1277

- https://tier4.atlassian.net/wiki/spaces/EMBIV/pages/3008168691/A+API

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR has been properly tested.
- [x] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Review by rokamu623 — APPROVED** [review]
LGTM!

**Review by rokamu623 — APPROVED** [review]
`caret_report` verification is succeed!
image

**Review by xygyo77 — COMMENTED** [review]
It may be a problem with my environment, but I get the following.

image

**Review by xygyo77 — APPROVED** [review]
I installed clear caret_report and it is now OK.

image

LGTM

**Pull request merged**
