### PR TITLE
chore: change local variable names

### PR DESCRIPTION
**Pull request by bopeng-saitama**
Signed-off-by: Bo Peng <82485734+bopeng-saitama@users.noreply.github.com>

Change local variable names / comment to fix the spell check error.

Changed word:

- byld -> by_ld
- timerstamp -> time_stamp
- keyname -> key_name 
- strct -> struct
- rects -> rect_list
- cbgs -> callback_groups 
- addrs -> addresses 
- lttngs -> lttng_list  
- ctrl -> control
- ctrls -> controls 
- maxs -> max_list 
- kargs -> kwargs

### CODE REVIEW

**Review by hsgwa — APPROVED** [review]
LGTM
I'll merge this PR after the next tag.

**Comment by hsgwa** [comment]
@bopeng-saitama 
One word seems missing.

https://github.com/tier4/CARET_analyze/blob/main/src/caret_analyze/common/singleton.py#L19
Could you please modify the following as well?
```
    def __new__(cls, *args, **kargs): # modify kargs to kwargs
```

I confirmed all python files passed spell check except for "kargs" !

```
find . -name "*.py" | xargs cspell -c .global.cspell.json
```
here, .global.cspell.json is https://github.com/tier4/autoware-spell-check-dict/blob/main/.cspell.json

**Comment by bopeng-saitama** [comment]
sure.I will do it right away.

**Review by hsgwa — APPROVED** [review]
LGTM!

pytest error is fixed by: https://github.com/tier4/CARET_analyze/pull/141

**Pull request merged**
