### PR TITLE
feat: response time all

### PR DESCRIPTION
**Pull request by rokamu623**
## Description
As a method for calculate `ResponseTime`, in addition to the existing worst/best, a method is implemented to calculate the `ResponseTime` from all inputs (even if the outputs are the same).

image

The following APIs have been added:
- `ResponseTime.to_all_records()`
  - return Records including response times for all case.
- `ResponseMapAll` class
  - generate Records which is returned by `ResponseTime.to_all_records()`.

## Related links
Jira: https://tier4.atlassian.net/browse/RT2-825

## Notes for reviewers
regression test of CARET_report
image

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Review by nabetetsu — COMMENTED** [review]
I think it also needs to test for error cases. For example, the value of end is greater than start.

**Comment by rokamu623** [comment]
@emori-ctc 
Please review this PR.

**Review by emori-ctc — APPROVED** [review]
Reviewed by.

**Comment by rokamu623** [comment]
@nabetetsu 
Please check this PR.

**Review by nabetetsu — APPROVED** [review]
I have confirmed that the changes works fine as expected. :+1:

**Pull request merged**
