### PR TITLE
fix: lttng and architecture call order dependency. disable lttng singleton

### PR DESCRIPTION
**Pull request by hsgwa**
Signed-off-by: hsgwa <hasegawa.isp@gmail.com>

### CODE REVIEW

**Review by takeshi-iwanari — DISMISSED** [review]
LGTM

**Comment by hsgwa** [comment]
I'll merge this PR after #75

**Comment by hsgwa** [comment]
@takeshi-iwanari 
Could you review this PR again?

**Review by takeshi-iwanari — APPROVED** [review]
LGTM

**Pull request merged**
