### PR TITLE
fix: support for bokeh 3.x

### PR DESCRIPTION
**Pull request by rokamu623**
## Description
support for bokeh version 2.x (3.3.0 latest).
the solution to one mypy error is debatable.

## Related links
Jira: https://tier4.atlassian.net/browse/RT2-792

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR has been properly tested.
- [x] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Review by bopeng-saitama — APPROVED** [review]
LGTM

**Comment by rokamu623** [comment]
@xygyo77 
Could you please review it?

**Review by xygyo77 — COMMENTED** [review]
When drawing a graph, I get "BokehUserWarning: out of range integer may result in loss of precision", is this as expected?

**Review by xygyo77 — APPROVED** [review]
Confirmed regarding bokeh versionup.

**Pull request merged**
